tasks:
  - name: Run Hedera Local Node
    init: >
        sudo apt-get update &&
        sudo apt-get install npm -y &&
        npm install &&
        npm run build &&
        sudo npm install -g
    command: hedera start -d

ports:
  - name: Consensus Node
    port: 50211
  - name: Mirror Node GRPC
    port: 5600
  - name: Mirror Node REST API
    port: 5551
  - name: Mirror Node API Proxy
    port: 8091
  - name: JSON RPC Relay
    port: 7546
  - name: JSON RPC Relay Websocket
    port: 8546
  - name: Block Node
    port: 8080
  - name: Mirror Node Explorer
    port: 8090
  - name: Grafana UI
    port: 3000
  - name: Prometheus UI
    port: 9090